server:
  port: 4321
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
